project_id = "dwopahjycvaocermgesw"

[functions.fetch-rss]
verify_jwt = false
schedule = "*/15 * * * *"

[functions.check-fetch-health]
verify_jwt = false
schedule = "*/30 * * * *"

[functions.mobile-api]
verify_jwt = false
